### ISSUE TITLE
http://thecodelesscode.com/ returns 403 Forbidden

### ISSUE THREAD

**Issue by cpcallen** [aldesantis/the-codeless-code#457]
Not sure that this is the correct place to report this, but when I try to access The Codeless Code, I get the following error message:

> Forbidden
> You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

I first noticed this a couple of days ago.

**Comment by aldesantis** [comment]
@QilessQi ^ 🙂

**Comment by QilessQi** [comment]
Thank you for your email, Christopher. The site was offlined this week by
my ISP for getting too much traffic.... and unfortunately I'm out of state
caring for a family member in the hospital.

It will be back, but probably not for another week.

Warmest regards,

Qi

**Comment by cpcallen** [comment]
@QilessQi: so sorry to hear of these difficulties.  I hope your family member will be OK.  Best wishes to both of you.

**Comment by Jogai** [comment]
Take your time. If you get to it it might help to use cloudflare.

**Comment by PeterWone** [comment]
How dare you publish content that people access! I wonder is there a case-235 in this?

**Comment by aldesantis** [comment]
Closing since this is now fixed!
